### ISSUE TITLE
Scrolling figure in fit all together pynb (diad 2 only)

### ISSUE THREAD

**Issue by cljdevitre** [PennyWieser/DiadFit#11]
Only diad 2 scrolls, not diad 1.
![scrolling figure](https://user-images.githubusercontent.com/103474333/210674808-4da9e244-c8d5-40ae-919c-0ce7a380bead.png)

**Comment by PennyWieser** [comment]
Fixed, this is a local issue, need to right click on cell and say disabled scrolling.
