### ISSUE TITLE
Stitch outputs together pynb throws error at cell 24 - too many exclude str

### ISSUE THREAD

**Issue by cljdevitre** [PennyWieser/DiadFit#13]
The cell has up to 4 exclude_str, but when running the cell it throws an error saying unexpected keyword. It would be nice to have the option for more than one or two exclude_str in get_diad_files if it isn't implemented already.

![stitchoutputs together error](https://user-images.githubusercontent.com/103474333/210871229-2d26636f-6f0c-4be1-a24b-10499e8d8e0a.png)

**Comment by PennyWieser** [comment]
Good spot, changed to exclude str as [...]
