### ISSUE TITLE
Merging error for secondary phases if Nonetype in Stitch outputs together pynb

### ISSUE THREAD

**Issue by cljdevitre** [PennyWieser/DiadFit#14]
Nonetype can't be merged. When only one secondary phase is present, merging fails (also fails if both are None ofc)

![Merging error with Nonetype in Stitch outputs](https://user-images.githubusercontent.com/103474333/210877870-ec87a9ab-95b6-48aa-b706-7a2ea7e0bb54.png)

**Comment by cljdevitre** [comment]
**Temporary solution to the 4 cells at the end of the stitch together notebook:**

### 1st cell ###
if os.path.exists(fitout_path+'/'+'CO3.xlsx'):
    Carb=pd.read_excel(fitout_path+'/'+'CO3.xlsx')
else:
    Carb=pd.DataFrame([])
if os.path.exists(fitout_path+'/'+'SO2.xlsx'):
    SO2=pd.read_excel(fitout_path+'/'+'SO2.xlsx')
else:
    SO2=pd.DataFrame([])

if (Carb.empty==False) & (SO2.empty==False):
    Sec_Phases=pd.merge(SO2, Carb, on='filename', how='outer')
    
if (Carb.empty==True) & (SO2.empty==False):
    Sec_Phases=SO2
if (Carb.empty==False) & (SO2.empty==True):
    Sec_Phases=Carb
if (Carb.empty==True) & (SO2.empty==True):
    Sec_Phases=pd.DataFrame([]) 
    print('You have no secondary phases!')

if Sec_Phases.empty==False:
    display(Sec_Phases.head())

### 2nd cell ###
# Remove these to get the pure file name
if Sec_Phases.empty==False:
    file_sec_phase=pf.extracting_filenames_generic(
        prefix=False, str_prefix=" ",
        names=Sec_Phases['filename'].reset_index(drop=True),
       file_type='.txt')

    display(file_sec_phase)

### 3rd cell ###
if Sec_Phases.empty==False:
    Sec_Phases['name_for_matching']=file_sec_phase
    df_combo['name_for_matching']=df_combo['filename_x']
    df_combo_sec_phase=df_combo.merge(Sec_Phases, on='name_for_matching', how='outer')

### 4th cell ###
if Sec_Phases.empty==False:
    df_combo_sec_phase.to_excel(fitout_path+'/'+'Calibration_fitting_w_sec_phases.xlsx')

**Comment by PennyWieser** [comment]
I *THINK* I have fixed this. cant think of a more elegant solution than a tonne of if statements as you say.
