### ISSUE TITLE
Discarded file/spectra generate 'inf' pressure

### ISSUE THREAD

**Issue by gleesonm1** [PennyWieser/DiadFit#21]
Combining the Strong, Medium, Weak, and Discarded files. 
The calculated CO2 density of any discarded spectra becomes 0 (splitting is NaN).
CO2 density of 0 returns an 'inf' value when entered into the EOS.

**Comment by PennyWieser** [comment]
Fixed in version 70 to replace any inf with Nan in the final dataframe
