### ISSUE TITLE
Compatibility issue with Python 3.11.3

### ISSUE THREAD

**Issue by cljdevitre** [PennyWieser/DiadFit#38]
fit_Ne_lines throws the following error when using Python 3.11.3
![Screenshot 2023-05-02 124344](https://user-images.githubusercontent.com/103474333/235772699-33167f8a-0d75-4641-adec-4d7db9af4a4f.png)

**Comment by PennyWieser** [comment]
Think this has been fixed. Isnt a python version issue - I think its a lmfit version issue that should now be resolved. Have asked charlotte to check lmfit version as I cant recreate this on python11

**Comment by PennyWieser** [comment]
lmfit issue I believe. Fixed for v.1.2.0
