### ISSUE TITLE
Update pf.propagate and other relevant function docstrings to reflect the use of XH2O forces calculations with Duan. 

### ISSUE THREAD

**Issue by cljdevitre** [PennyWieser/DiadFit#60]
Might be good to update the docstring just to mention under EOS or under the general description that if you pick a XH2O it will use the DZ EOS?

**Comment by PennyWieser** [comment]
What versoin were you on? It should print this it swaps to DZ06? 
![image](https://github.com/PennyWieser/DiadFit/assets/65668673/2117a6dc-82f3-4d74-a71c-6215aa60130d)
