### ISSUE TITLE
The docstring description for H_loss and no_H_loss is the same.

### ISSUE THREAD

**Issue by cljdevitre** [PennyWieser/DiadFit#62]
specifically         
P_kbar_mixCO2_DZ06_Hloss: Pressure calculated from the reconstructed mixed fluid density using the mixed EOS from Duan and Zhang (2006) assuming H loss
P_kbar_mixCO2_DZ06_noHloss: Pressure calculated from the reconstructed mixed fluid density using the mixed EOS from Duan and Zhang (2006) assuming H loss
P Mix_Hloss/P Pure DZ06: Correction factor - e.g. how much deeper the pressure is from the mixed EOS with H loss
P Mix_noHloss/P Pure DZ06: Correction factor - e.g. how much deeper the pressure is from the mixed EOS with H loss

![image](https://github.com/PennyWieser/DiadFit/assets/103474333/56d52b5c-b454-4e00-bbc6-8716151b1ac1)

**Comment by PennyWieser** [comment]
fixed
