### ISSUE TITLE
pf.calculate_entrapment_P_XH2O fails at specific density, XH2O and P

### ISSUE THREAD

**Issue by cljdevitre** [PennyWieser/DiadFit#63]
![image](https://github.com/PennyWieser/DiadFit/assets/103474333/d038c0a6-184d-4d91-b2b6-88407d4c6506)

**Comment by PennyWieser** [comment]
This was an error relating to the calculation of density without H2O loss. Adapted now to use partial pressure law, and correct XH2O by mass to be proportion not mass ratio.
