### ISSUE TITLE
Missing if statement in fit_generic_peak, does not allow not to plot figures.

### ISSUE THREAD

**Issue by cljdevitre** [PennyWieser/DiadFit#8]
fit_generic_peak Always plots figures, even when plot_figure=False, there is no if statement at line 2790 to enable the user choose whether to plot figures or not.
![missing plot false option](https://user-images.githubusercontent.com/103474333/205762120-9601e07f-9ba8-4da1-8ecc-3d7aa7a989d4.png)

**Comment by PennyWieser** [comment]
Added
