### ISSUE TITLE
Adding an exclude_str to get_Ne_files and a conditional so it doesn't fail if one doesn't specify an exclude str. 

### ISSUE THREAD

**Issue by cljdevitre** [PennyWieser/DiadFit#9]
get_Ne_files will not work if no exclude_str is specified (default Nonetype breaks it). 
Additionally, it would be nice to have the option to exclude more than one string. 

Screenshot of suggestion for get_Ne_files, provides both (user can specify one, two or no characters to exclude using exclude str and exclude_str2).
There is probably a more elegant way to do it, but this works (tested). 

![get_Ne_files suggestion](https://user-images.githubusercontent.com/103474333/205790558-69dbf0c5-69ba-4f54-89f2-78118363f705.png)

**Comment by PennyWieser** [comment]
All combined into get_files function now
